add_rules("mode.debug", "mode.release")

task("merge")
    on_run(function()
        -- 生成时间戳
        local timestamp = os.date("%Y-%m-%d %H:%M:%S")

        -- 运行合并命令
        os.exec("xmake l cli.amalgamate -o . validate")

        -- 测试使用
        os.exec("xmake l cli.amalgamate validate")
        -- 读取生成的内容
        local content = io.readfile("validate.h")

        -- 注入版本信息
        local header = string.format([[
// ==================================================
// Auto-generated by xmake amalgamate
// Time: %s
// ==================================================
#ifndef _SVPCET_
#define _SVPCET_
]], timestamp)

        local footer = [[
#endif // _SVPCET_ 
        ]]

        -- 重新写入文件
        io.writefile(validate.h", header .. content .. footer)
    end)
    set_menu {
        description = "合并头文件"
    }

target("validate")
    set_kind("headeronly")
    add_includedirs("src") 
    add_headerfiles("src/include_all.h")

target("tests")
    set_kind("binary")
    add_cxxflags("/utf-8") 
    set_languages("cxx17")
    add_files("test/*.cpp")
    add_files("test/catch/catch_amalgamated.cpp")
    add_files("test/algorithm/*.cpp")
    add_includedirs("./test/catch")
    add_includedirs("src")
    add_deps("validate")

task("run_test")
    on_run(function()
        import("core.base.task")
        import("core.base.option")
        
        task.run("build", {target = "tests"})
        
        local tags = option.get("tags")
        local test_cmd = "xmake run tests"
        
        if tags then
            test_cmd = test_cmd .. " " .. tags
        end
        
        os.exec(test_cmd)
        
    end)
    set_menu {
        options = {
            {"t", "tags", "kv", nil, "Catch2标签过滤（如 [tag1][tag2]）"},
        },
        description = "运行测试"
    }